### ISSUE TITLE
Game Desc. Page

### ISSUE THREAD

**Issue by EmmaMartin123** [ke444a/cw2_api_mashup#3]
Lucy

**Comment by LTmsn** [comment]
Make a general page which can be used for all games which just depends on the name of the game/api url

[] Display Game name
[] Carousel of screenshots/game cover images
[] Reviews of the game
[] Game rating on the right of reviews
[] List of platforms
[] Store links

**Comment by LTmsn** [comment]
I just did a base description page with lorem ipsum so that Alex can start working on the api side of it (there isnt a nav or footer yet btw)
