### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by EmmaMartin123** [ke444a/cw2_api_mashup#4]

**Comment by ke444a** [comment]
- [ ] Create Home page
   - [x] Design introduction for the page
   - [x] Create a placeholding carousel for Special Offers
   - [x] Create a placeholding carousel for Top Deals
   - [x] Create rows with game cards for New Releases
   - [ ] Create a section that refers to the "Search by Category" page
   - [ ] Add responsive design for the whole page
