### ISSUE TITLE
Repeated Designs

### ISSUE THREAD

**Issue by EmmaMartin123** [ke444a/cw2_api_mashup#5]
- [x] Logo

**Comment by HendersonFlynn** [comment]
![VapourLogoWithoutBackground](https://user-images.githubusercontent.com/114341040/204164376-a997003d-3592-421d-97c0-33cc787c3104.png)
![VapourLogoWithBackground](https://user-images.githubusercontent.com/114341040/204164384-71874def-bd9a-44f5-95e3-73455f78f98c.png)

**Comment by HendersonFlynn** [comment]
Forgot to mention, top one has a transparent Background, bottom one features the gradient.

**Comment by HendersonFlynn** [comment]
![VapourLogoWithBackgroundWithoutText](https://user-images.githubusercontent.com/114341040/204398890-9e40cd67-a61d-4f76-af53-9fd33409cd80.png)
![VapourLogoWithoutBackgroundWithoutText](https://user-images.githubusercontent.com/114341040/204398903-4c6ac9f0-a53c-4770-a488-cb699dc09d68.png)
@ke444a As requested

**Comment by HendersonFlynn** [comment]
- [ ] Mascot

**Comment by HendersonFlynn** [comment]
![GameBackGroundSpread](https://user-images.githubusercontent.com/114341040/208113064-408f5a6d-034b-422d-95a5-81775aba0c3d.png)

**Comment by HendersonFlynn** [comment]
![GameSpreadGradient](https://user-images.githubusercontent.com/114341040/208113851-50ad38b7-2963-4518-8b62-2a75985859e8.png)
